openapi: 3.0.2

info:
  title: Minesweeper API
  description: API used for the MineSweeper game
  version: 1.0.0
paths:
  /games:
    post:
      tags:
        - Game
      summary: Creates a new MineSweeper game
      description: Creates a new MineSweeper game
      operationId: createGame
      responses:
        200:
          description: Game created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameResponse"
              example:
                gameId: 3160c9de-b152-4886-ae52-41f670c493e9
        405:
          description: Method not allowed error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MethodNotAllowedErrorResponse"
components:
  schemas:
    GameResponse:
      type: object
      properties:
        backupId:
          type: string
          description: Game id
          example: "3160c9de-b152-4886-ae52-41f670c493e9"
    MethodNotAllowedErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: timestamp of the response
          example: "2020-05-30T21:09:11.897+0000"
        status:
          type: integer
          description: http status code
          example: 405
        error:
          type: string
          description: Description of the error
          example: "Method Not Allowed"
        message:
          type: string
          description: Message of the response
          example: ""
        path:
          type: string
          description: Path called
          example: "/endpoint"